# Generated by Django 4.2.6 on 2023-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='artworks',
        ),
        migrations.AddField(
            model_name='collection',
            name='selected_artworks',
            field=models.ManyToManyField(blank=True, to='collection.artwork'),
        ),
    ]
