# Generated by Django 4.2.6 on 2023-11-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_remove_collection_artworks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='selected_artworks',
        ),
        migrations.AddField(
            model_name='collection',
            name='artworks',
            field=models.ManyToManyField(to='collection.artwork'),
        ),
    ]
